logging:
  level:
    root: INFO
#    com:
#      okta: TRACE
    org:
      springframework:
        security: INFO

#  pattern:
#    correlation: [{traceId:-},{spanId:-}]

spring:
  application:
      name: fss


  jmx:
    enabled: false

  datasource:

    url: jdbc:postgresql://localhost:5432/fss?sslmode=disable
    username: kgignatyev
    password:
    driver-class-name: org.postgresql.Driver
    hikari:
      minimum-idle: 10
      connection-init-sql: SELECT 1
      maximum-pool-size: 20
      catalog: jobs

  flyway:
    baseline-on-migrate: true
    default-schema: jobs

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        default_schema: jobs

  cache:
    type: HAZELCAST


  hazelcast:
    config: classpath:hazelcast.xml



  temporal:
    connection:
      #uncomment when temporal server is up and running, temporal beans are conditional on
#      the property
      target: 127.0.0.1:7233
      target.namespace: default
    workersAutoDiscovery:
      packages: com.kgignatyev.fss.service


management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      base-path: /actuator
    health:
      sensitive: false
  simple:
    metrics:
      export:
        enabled: true


okta:
  oauth2:
    # Replace with the domain of your Auth0 tenant.
    issuer: https://kgignatyev.auth0.com/
    # Replace with the API Identifier for your Auth0 API.
    audience: http://local-dev

casbin:
  enable-log: true



